### ISSUE TITLE
Installation issue (create terminal job failed)

### ISSUE THREAD

**Issue by RGerzaguet** [fannheyward/coc-julia#251]
Hello,
 I get a weird issue when I try to install coc-julia on an Ubuntu 18.04  with coc-nvim (updated to last version) and coc-julia (version 0.10)
The installation works fine 
```
coc-julia Installed extension coc-julia@0.10.0 
```
But when afterwards I open a Julia file and I am asked to install some compile_env deps, I get immediately (after typing yes) the following error 
```
Error on activate extension coc-julia: request error nvim_call_function - create terminal job failed 
```

I get some log with the `coc#client#open_log()` that I put afterwards even if it is quite wordy that I have put [here](https://gist.github.com/RGerzaguet/cbdad814ac0108e2357ae2884e2edf76)

How can I solve that ?

**Comment by fannheyward** [comment]
What's your `:CocInfo`?

**Comment by RGerzaguet** [comment]
Thanks for the quick reply !
Here it is 

```
## versions

vim version: VIM - Vi IMproved 8.0 0
node version: v16.8.0
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /home/rgerzagu/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2021-09-09T10:44:46.053 INFO (pid:24242) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v16.8.0 after 66ms
2021-09-09T10:44:48.807 ERROR (pid:24242) [node-client] - request error on "nvim_call_function" [
  'coc#terminal#start',
  [ [ '/bin/bash' ], '/home/rgerzagu/Documents/oraclecnn.jl', {} ]
] create terminal job failed Error
    at wF.request (/home/rgerzagu/.vim/plugged/coc.nvim/build/index.js:30:34430)
    at wF.call (/home/rgerzagu/.vim/plugged/coc.nvim/build/index.js:33:3671)
    at Ug.start (/home/rgerzagu/.vim/plugged/coc.nvim/build/index.js:180:2429)
    at Uj.createTerminal (/home/rgerzagu/.vim/plugged/coc.nvim/build/index.js:182:5446)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Ctx.resolveMissingPkgs (/home/rgerzagu/.config/coc/extensions/node_modules/coc-julia/lib/index.js:351:9)
    at async Ctx.startServer (/home/rgerzagu/.config/coc/extensions/node_modules/coc-julia/lib/index.js:407:5)
    at async Object.activate (/home/rgerzagu/.config/coc/extensions/node_modules/coc-julia/lib/index.js:470:3)
2021-09-09T10:44:48.809 ERROR (pid:24242) [extensions] - Error on active extension coc-julia: request error nvim_call_function - create terminal job failed Error
    at wF.request (/home/rgerzagu/.vim/plugged/coc.nvim/build/index.js:30:34430)
    at wF.call (/home/rgerzagu/.vim/plugged/coc.nvim/build/index.js:33:3671)
    at Ug.start (/home/rgerzagu/.vim/plugged/coc.nvim/build/index.js:180:2429)
    at Uj.createTerminal (/home/rgerzagu/.vim/plugged/coc.nvim/build/index.js:182:5446)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Ctx.resolveMissingPkgs (/home/rgerzagu/.config/coc/extensions/node_modules/coc-julia/lib/index.js:351:9)
    at async Ctx.startServer (/home/rgerzagu/.config/coc/extensions/node_modules/coc-julia/lib/index.js:407:5)
    at async Object.activate (/home/rgerzagu/.config/coc/extensions/node_modules/coc-julia/lib/index.js:470:3)
2021-09-09T10:45:49.094 INFO (pid:24242) [attach] - Request action: snippetCheck [ 1, 1 ]
```

**Comment by fannheyward** [comment]
Tested with nvim, can't reproduce this. From the error logs, `coc#terminal#start` is failed to run, https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/terminal.vim#L60-L71, it just called `term_start` to create terminal, seems like this is related vim 8.0, can you test with a newer vim?

**Comment by RGerzaguet** [comment]
Ok, with vim 8.2 the error disappears.
Thanks @fannheyward :)
