### ISSUE TITLE
[coc.nvim]: Unhandled response error -32097 from language server: Pending response rejected since connection got disposed

### ISSUE THREAD

**Issue by jclsn** [fannheyward/coc-julia#465]
For me the language serverfails with the above message. Here are the logs

```
## versions

vim version: VIM - Vi IMproved 9.1 9010252
node version: v21.7.2
coc.nvim version: 0.0.82-ede39ea9 2024-03-28 17:57:50 +0800
coc.nvim directory: /home/jan/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2024-04-13T13:40:16.440 INFO (pid:46317) [extension:coc-git] - Looking for git in: git
2024-04-13T13:40:16.611 INFO (pid:46317) [plugin] - coc.nvim initialized with node: v21.7.2 after 381
2024-04-13T13:40:16.613 INFO (pid:46317) [services] - LanguageClient julia state change: stopped => starting
2024-04-13T13:40:16.621 INFO (pid:46317) [language-client-index] - Language server "languageserver.julia" started with 46339
2024-04-13T13:40:18.536 INFO (pid:46317) [services] - LanguageClient julia state change: starting => stopped
2024-04-13T13:40:18.536 INFO (pid:46317) [services] - LanguageClient julia state change: stopped => starting
2024-04-13T13:40:18.537 ERROR (pid:46317) [language-client-client] - Server languageserver.julia initialization failed. n [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/home/jan/.vim/plugged/coc.nvim/build/index.js:49:4693)
    at Object.dispose (/home/jan/.vim/plugged/coc.nvim/build/index.js:244:6205)
    at bd.handleConnectionClosed (/home/jan/.vim/plugged/coc.nvim/build/index.js:247:15479)
    at bd.handleConnectionClosed (/home/jan/.vim/plugged/coc.nvim/build/index.js:251:3557)
    at t (/home/jan/.vim/plugged/coc.nvim/build/index.js:247:15128)
    at yP.invoke (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:14324)
    at n.fire (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:15094)
    at On (/home/jan/.vim/plugged/coc.nvim/build/index.js:23:5915)
    at yP.invoke (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:14324)
    at n.fire (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:15094) {
  code: -32097,
  data: undefined
}
2024-04-13T13:40:18.539 INFO (pid:46317) [services] - LanguageClient julia state change: starting => stopped
2024-04-13T13:40:18.540 ERROR (pid:46317) [server] - unhandledRejection  Promise {
  <rejected> n [Error]: Pending response rejected since connection got disposed
      at Object.dispose (/home/jan/.vim/plugged/coc.nvim/build/index.js:49:4693)
      at Object.dispose (/home/jan/.vim/plugged/coc.nvim/build/index.js:244:6205)
      at bd.handleConnectionClosed (/home/jan/.vim/plugged/coc.nvim/build/index.js:247:15479)
      at bd.handleConnectionClosed (/home/jan/.vim/plugged/coc.nvim/build/index.js:251:3557)
      at t (/home/jan/.vim/plugged/coc.nvim/build/index.js:247:15128)
      at yP.invoke (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:14324)
      at n.fire (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:15094)
      at On (/home/jan/.vim/plugged/coc.nvim/build/index.js:23:5915)
      at yP.invoke (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:14324)
      at n.fire (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:15094) {
    code: -32097,
    data: undefined
  }
} n [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/home/jan/.vim/plugged/coc.nvim/build/index.js:49:4693)
    at Object.dispose (/home/jan/.vim/plugged/coc.nvim/build/index.js:244:6205)
    at bd.handleConnectionClosed (/home/jan/.vim/plugged/coc.nvim/build/index.js:247:15479)
    at bd.handleConnectionClosed (/home/jan/.vim/plugged/coc.nvim/build/index.js:251:3557)
    at t (/home/jan/.vim/plugged/coc.nvim/build/index.js:247:15128)
    at yP.invoke (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:14324)
    at n.fire (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:15094)
    at On (/home/jan/.vim/plugged/coc.nvim/build/index.js:23:5915)
    at yP.invoke (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:14324)
    at n.fire (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:15094) {
  code: -32097,
  data: undefined
}
2024-04-13T13:40:18.542 INFO (pid:46317) [language-client-index] - Language server "languageserver.julia" started with 46357
2024-04-13T13:40:20.466 INFO (pid:46317) [services] - LanguageClient julia state change: stopped => starting
2024-04-13T13:40:20.466 ERROR (pid:46317) [language-client-client] - Server languageserver.julia initialization failed. n [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/home/jan/.vim/plugged/coc.nvim/build/index.js:49:4693)
    at Object.dispose (/home/jan/.vim/plugged/coc.nvim/build/index.js:244:6205)
    at bd.handleConnectionClosed (/home/jan/.vim/plugged/coc.nvim/build/index.js:247:15479)
    at bd.handleConnectionClosed (/home/jan/.vim/plugged/coc.nvim/build/index.js:251:3557)
    at t (/home/jan/.vim/plugged/coc.nvim/build/index.js:247:15128)
    at yP.invoke (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:14324)
    at n.fire (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:15094)
    at On (/home/jan/.vim/plugged/coc.nvim/build/index.js:23:5915)
    at yP.invoke (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:14324)
    at n.fire (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:15094) {
  code: -32097,
  data: undefined
}
2024-04-13T13:40:20.466 INFO (pid:46317) [services] - LanguageClient julia state change: starting => stopped
2024-04-13T13:40:20.466 ERROR (pid:46317) [services] - Server languageserver.julia failed to start: n [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/home/jan/.vim/plugged/coc.nvim/build/index.js:49:4693)
    at Object.dispose (/home/jan/.vim/plugged/coc.nvim/build/index.js:244:6205)
    at bd.handleConnectionClosed (/home/jan/.vim/plugged/coc.nvim/build/index.js:247:15479)
    at bd.handleConnectionClosed (/home/jan/.vim/plugged/coc.nvim/build/index.js:251:3557)
    at t (/home/jan/.vim/plugged/coc.nvim/build/index.js:247:15128)
    at yP.invoke (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:14324)
    at n.fire (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:15094)
    at On (/home/jan/.vim/plugged/coc.nvim/build/index.js:23:5915)
    at yP.invoke (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:14324)
    at n.fire (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:15094) {
  code: -32097,
  data: undefined
}
2024-04-13T13:40:20.469 INFO (pid:46317) [language-client-index] - Language server "languageserver.julia" started with 46374
2024-04-13T13:40:22.384 INFO (pid:46317) [services] - LanguageClient julia state change: stopped => starting
2024-04-13T13:40:22.385 ERROR (pid:46317) [language-client-client] - Server languageserver.julia initialization failed. n [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/home/jan/.vim/plugged/coc.nvim/build/index.js:49:4693)
    at Object.dispose (/home/jan/.vim/plugged/coc.nvim/build/index.js:244:6205)
    at bd.handleConnectionClosed (/home/jan/.vim/plugged/coc.nvim/build/index.js:247:15479)
    at bd.handleConnectionClosed (/home/jan/.vim/plugged/coc.nvim/build/index.js:251:3557)
    at t (/home/jan/.vim/plugged/coc.nvim/build/index.js:247:15128)
    at yP.invoke (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:14324)
    at n.fire (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:15094)
    at On (/home/jan/.vim/plugged/coc.nvim/build/index.js:23:5915)
    at yP.invoke (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:14324)
    at n.fire (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:15094) {
  code: -32097,
  data: undefined
}
2024-04-13T13:40:22.385 INFO (pid:46317) [services] - LanguageClient julia state change: starting => stopped
2024-04-13T13:40:22.387 INFO (pid:46317) [language-client-index] - Language server "languageserver.julia" started with 46386
2024-04-13T13:40:24.362 ERROR (pid:46317) [language-client-client] - Server languageserver.julia initialization failed. n [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/home/jan/.vim/plugged/coc.nvim/build/index.js:49:4693)
    at Object.dispose (/home/jan/.vim/plugged/coc.nvim/build/index.js:244:6205)
    at bd.handleConnectionClosed (/home/jan/.vim/plugged/coc.nvim/build/index.js:247:15479)
    at bd.handleConnectionClosed (/home/jan/.vim/plugged/coc.nvim/build/index.js:251:3557)
    at t (/home/jan/.vim/plugged/coc.nvim/build/index.js:247:15128)
    at yP.invoke (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:14324)
    at n.fire (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:15094)
    at On (/home/jan/.vim/plugged/coc.nvim/build/index.js:23:5915)
    at yP.invoke (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:14324)
    at n.fire (/home/jan/.vim/plugged/coc.nvim/build/index.js:19:15094) {
  code: -32097,
  data: undefined
}
2024-04-13T13:40:54.892 INFO (pid:46317) [attach] - receive notification: showInfo []
```

**Comment by fannheyward** [comment]
> Language server "languageserver.julia" started with 46339

@jclsn you're mixed using `languageserver.julia` and coc-julia, remove `languageserver.julia` from your coc-settings.json

@angelpilled the `connection got disposed` error means Julia language server failed to start to run, the client, coc.nvim/coc-julia, couldn't connect to the server. Check the server status:

```
❯ julia --project=/Users/fannheyward/.config/coc/extensions/node_modules/coc-julia/server
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.10.2 (2024-03-01)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(server) pkg> st
Status `~/.config/coc/extensions/node_modules/coc-julia/server/Project.toml`
⌃ [2b0e0bc5] LanguageServer v4.4.0
⌃ [9b87118b] PackageCompiler v2.1.5
Info Packages marked with ⌃ have new versions available and may be upgradable.

(server) pkg>
```

**Comment by jclsn** [comment]
I am back working on Julia again. I uninstalled LanguageServer.jl and ran the command you posted. Now it is not crashing anymore, but is showing ``⠋ Initializing julia`` forever

**Comment by jclsn** [comment]
Ah nevermind, I think it was conflicting with the ``vim-julia`` plugin
